CREATE TABLE posts (
	id INTEGER PRIMARY KEY,
	added TEXT DEFAULT CURRENT_TIMESTAMP,
	rating TEXT,
	mime TEXT,
	key TEXT
);

CREATE TABLE tags (
	id INTEGER PRIMARY KEY,
	name TEXT,
	type TEXT
);

CREATE TABLE posts_tags (
	pid INTEGER,
	tid INTEGER,
	FOREIGN KEY(pid) REFERENCES posts(id) ON DELETE CASCADE,
	FOREIGN KEY(tid) REFERENCES tags(id) ON DELETE CASCADE,
	UNIQUE(pid, tid) ON CONFLICT REPLACE
);

CREATE TRIGGER clear_empty_tags AFTER DELETE ON posts_tags
BEGIN
	DELETE FROM tags WHERE id NOT IN (SELECT tid FROM posts_tags);
END;
